name: Greenroom Backstage Build
on: [push]
jobs:
  Greenroom-Backstage-Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # AWS Access Key and Secret Key version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # OIDC AWS cred version
      #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-region: ap-southeast-2
      #    role-to-assume: arn:aws:iam::803304326831:role/GitHub_Actions
      #    role-session-name: GitHubActions_Backstage
      #- name: Login to Amazon ECR
      #  id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v1

      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Build Backstage host
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn build
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: greenroom/docker/Dockerfile
          tags: 803304326831.dkr.ecr.ap-southeast-2.amazonaws.com/backstage:latest
          push: true
